# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

# Setup XDG for screen sharing
exec-once = ~/Projects/dotfiles/configs/hypr/scripts/xdg.sh

# Start Polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Dunst Notification Manager
exec-once = dunst

# Load GTK settings

# Using hypridle to start hyprlock
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Initialize swww
exec-once = swww query || swww init

# Initialize wallpaper
exec-once = ~/Projects/dotfiles/configs/hypr/scripts/wallpaper.sh

# Initialize waybar
exec-once = waybar